version: '2'
services:
    sv_football-app:
        image: sv_football
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://sv_football-mysql:3306/sv_football?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    sv_football-mysql:
        extends:
            file: mysql.yml
            service: sv_football-mysql
